name: CI-CD Flask Docker

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: |
          cd app
          docker build -t flask-app .

      - name: Desplegar en EC2 por SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/mi-repositorio-devops/app
            docker compose down
            docker compose up -d --build